In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3,4,5]

In [ ]:
print(mylist)

[1, 2, 3, 4, 5]


In [ ]:
np1 = np.array([1,2,3,4,5])

In [ ]:
print(np1) #1d array

[1 2 3 4 5]


In [ ]:
type(np1)

numpy.ndarray

In [ ]:
np2 = np.array((1,2,3,4,5))

In [ ]:
np2 #1d array

array([1, 2, 3, 4, 5])

In [ ]:
print(np2)

[1 2 3 4 5]


In [ ]:
type(np2)

numpy.ndarray

In [ ]:
np3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
np3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np1d = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
np1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np4 = np.array([[[4,6],[7,8]],[[1,2],[3,4]],[[0,1],[2,3]]])

In [ ]:
np4

array([[[4, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]],

       [[0, 1],
        [2, 3]]])

In [ ]:
type(np4)

numpy.ndarray

In [ ]:
np3 = np.array([[1,2,3.2],[4,5,6],[7,8,9]], dtype=float)

In [ ]:
np3

array([[1. , 2. , 3.2],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [ ]:
np5 = np.array([5.1,-1,"s",2])

In [ ]:
#"s" - number?

In [ ]:
#when array contains a char and number, number will be converted to character

In [ ]:
np5

array(['5.1', '-1', 's', '2'], dtype='<U32')

In [ ]:
np6 = np.array([[2.4,1],[4.4,2],[2.1,1]])

In [ ]:
#when there is an int, float, int will be converted to a float

In [ ]:
#char > float > int

In [ ]:
np6

array([[2.4, 1. ],
       [4.4, 2. ],
       [2.1, 1. ]])

In [ ]:
np6.ndim

2

In [ ]:
np5.ndim

1

In [ ]:
np4.ndim

3

In [ ]:
np6.shape

(3, 2)

In [ ]:
np4.shape

(3, 2, 2)

In [ ]:
np5.shape

(4,)

In [ ]:
np6.size

6

In [ ]:
np4.size

12

In [ ]:
np5.size

4

In [ ]:
#ndim - 1d, 2d, 3d?
#shape - rows, cols?
#size - individual elements?

In [ ]:
np6.dtype

dtype('<U32')

In [ ]:
np4.dtype

dtype('int64')

In [ ]:
np5.dtype

dtype('<U32')

In [ ]:
np6.itemsize

128

In [ ]:
np4.itemsize

4

In [ ]:
np5.itemsize

44

In [ ]:
np4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
np5

array(['5.1', '-1', 's', '2'], dtype='<U32')

In [ ]:
np5[3]

np.str_('2')

In [ ]:
np5[0:3]

array(['5.1', '-1', 's'], dtype='<U32')

In [ ]:
np6

array([[2.4, 1. ],
       [4.4, 2. ],
       [2.1, 1. ]])

In [ ]:
np6[1,1]

np.float64(2.0)

In [ ]:
np4 #[2darray,rows, cols] [1,1,1]

array([[[4, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]],

       [[0, 1],
        [2, 3]]])

In [ ]:
np4[0,0,0]

np.int64(4)

In [ ]:
np1 = np.array([1,2,3,4,5])

In [ ]:
np1

array([1, 2, 3, 4, 5])

# Masking: To hide something

In [ ]:
m1 = np.array([True, True, False, False, False]) #masking

In [ ]:
m1

array([ True,  True, False, False, False])

In [ ]:
np1[m1]

array([1, 2])

In [ ]:
np2

array([1, 2, 3, 4, 5])

In [ ]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
np3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
m2 = np.array([[True, True, False],[True, False, True],[False, False, True]])

In [ ]:
m2

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [ ]:
np3[m2]

array([1, 2, 4, 6, 9])

In [ ]:
np4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
m4 = np.array([[[True,False],[True,False]],[[True,False],[True,False]]])

In [ ]:
np4[m4]

array([1, 3, 5, 7])

In [ ]:
np3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np3[0:1,0:1]

array([[1]])

In [ ]:
np3[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
np4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
np4[0:2,0:1,0:1]

array([[[1]],

       [[5]]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
c = a + b

In [ ]:
print(c)

[5 7 9]


In [ ]:
c = a - b

In [ ]:
print(c)

[-3 -3 -3]


In [ ]:
c = a * b

In [ ]:
print(c)

[ 4 10 18]


In [ ]:
c = b / a

In [ ]:
print(c)

[4.  2.5 2. ]


In [ ]:
a

array([1, 2, 3])

In [ ]:
h = a ** 3

In [ ]:
h

array([ 1,  8, 27])

In [ ]:
c = b % a

In [ ]:
a ** b

array([  1,  32, 729])

In [ ]:
c

array([0, 1, 0])

In [ ]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
np3.transpose()

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [ ]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
np1

array([1, 2, 3, 4, 5])

In [ ]:
np1 = np.array([5,1,3,4,2])

In [ ]:
np1

array([5, 1, 3, 4, 2])

In [ ]:
np.sort(np1)

array([1, 2, 3, 4, 5])

In [ ]:
np2 = np.array([[5,2,3],[7,1,6],[8,4,9]])

In [ ]:
np2

array([[5, 2, 3],
       [7, 1, 6],
       [8, 4, 9]])

In [ ]:
np.sort(np2)

array([[2, 3, 5],
       [1, 6, 7],
       [4, 8, 9]])

In [ ]:
np.sort(np2, axis = 1)

array([[2, 3, 5],
       [1, 6, 7],
       [4, 8, 9]])

In [ ]:
np.sort(np2,axis = 0)

array([[5, 1, 3],
       [7, 2, 6],
       [8, 4, 9]])

In [ ]:
#1 - rows will be sorted individually in asc
#0 - cols will be sorted individually in asc
#none - by default rows will be sorted individually

In [ ]:
np.sort(np2, axis = 1)

array([[2, 3, 5],
       [1, 6, 7],
       [4, 8, 9]])

In [ ]:
np1

array([5, 1, 3, 4, 2])

In [ ]:
np.sort(np1)

array([1, 2, 3, 4, 5])

In [ ]:
np.argsort(np1)

array([1, 4, 2, 3, 0])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([4, 5, 6])

In [ ]:
np.concatenate((b,a))

array([4, 5, 6, 1, 2, 3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
c = np.array([4,5])

In [ ]:
c

array([4, 5])

In [ ]:
np.concatenate((a,c))

array([1, 2, 3, 4, 5])

In [ ]:
a1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2 = np.array([[7,8],[9,10]])

In [ ]:
a2

array([[ 7,  8],
       [ 9, 10]])

In [ ]:
np.concatenate((a1,a2), axis = 1)

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

In [ ]:
np.concatenate((a1,a2), axis = 0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
n1 = np.array([1,2,3,4,5,6]) #1,6 or 6,1 or 23 or 32

In [ ]:
n1

array([1, 2, 3, 4, 5, 6])

In [ ]:
n1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
n1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
n1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
n1.reshape(6,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [ ]:
n1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
n3 = n1.reshape(2,3,2) #2 - 2darrays , rows - 3, cols - 2

In [ ]:
n3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
np2

array([[5, 2, 3],
       [7, 1, 6],
       [8, 4, 9]])

In [ ]:
np2.reshape(-1) #flattening the array

array([5, 2, 3, 7, 1, 6, 8, 4, 9])

In [ ]:
n3

NameError: name 'n3' is not defined

In [ ]:
n3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
n3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.split(n1,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [ ]:
np2

array([[5, 2, 3],
       [7, 1, 6],
       [8, 4, 9]])

In [ ]:
np.mean(np2)

5.0

In [ ]:
np.mean(np2, axis = 0)

array([6.66666667, 2.33333333, 6.        ])

In [ ]:
np.mean(np2, axis = 1)

array([3.33333333, 4.66666667, 7.        ])

#median, std, min, max, sum

In [ ]:
np0 = np.ones(5)

In [ ]:
np0

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [ ]:
np.full((2,4), -1)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [ ]:
np.full((2,4,2), -4)

array([[[-4, -4],
        [-4, -4],
        [-4, -4],
        [-4, -4]],

       [[-4, -4],
        [-4, -4],
        [-4, -4],
        [-4, -4]]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4,4,1) #Move diagonal elements up by 1

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4,4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.eye(4,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
np.eye(4,4,-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [ ]:
np.eye(4,4,0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4,4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,11,5) #numbers between 2 and 10 with step size 5

array([2, 7])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.random(5) #random 5 numbers between 0 and 1

array([0.08370108, 0.69528965, 0.23393094, 0.96768355, 0.96183089])

In [ ]:
np.random.random((2,3)) #random numbers in 2 rows and 3 columns

array([[0.48680872, 0.62260203, 0.60127128],
       [0.8709712 , 0.459482  , 0.0867309 ]])

In [ ]:
np.random.random((2,2,3))

array([[[0.70126743, 0.72409458, 0.92600035],
        [0.27402032, 0.48844136, 0.99161438]],

       [[0.74824153, 0.92772133, 0.99985563],
        [0.87974777, 0.28703792, 0.97508425]]])

In [ ]:
np.linspace(1,10,5) #numbers between 1 and 10 with 5 equal parts(distance)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])