In [4]:
import numpy as np

In [5]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [6]:
a

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
b = np.zeros((3, 4))

In [9]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
b.ndim

2

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(5, dtype=int) #Return a new array of given shape and type, filled with ones

array([1, 1, 1, 1, 1])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.twos(5) #doesn't exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [15]:
np.array([[2, 2, 2,], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [16]:
arr = np.zeros((3, 4))

In [17]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#3 dimensionaly array
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#3 dimensionaly array
arr = np.zeros((3, 3, 4))


In [22]:
arr


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
arr.ndim

3

In [24]:
np.zeros((1, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
b = np.zeros((1, 1, 3, 3))
b

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [27]:
b.ndim

4

In [29]:
c = np.zeros((1, 1, 1, 3, 3))
c

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [30]:
c.ndim

5

In [32]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
a=arr+6
a

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [36]:
a * 2

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [37]:
a - 1

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [38]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries.It means entries in the array can be anything random values

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
# Random Module
import random
random.choice((1, 2, 3, 4, 5)) #Random number from given number

4

In [ ]:
random.choice("Vikash") #Random character from giver word

'a'

In [ ]:
random.randrange(1, 10) #Random number from given range

4

In [44]:
random.random() #a random no generated between 0(included) and 1(excluded)

0.46352935183567645

In [45]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [ ]:
random.shuffle(lis) #reshuffle the value in list

In [47]:
lis

[4, 2, 3, 1, 5]

In [ ]:
random.uniform(7, 14) #choosen as per uniform probability between 7 to 13

12.788089083272308

In [49]:
#random numbers related concept in numpy

np.array([])

array([], dtype=float64)

In [50]:
np.random.random_sample()

0.19483114796618062

In [51]:
np.random.random_sample((5, )) #1 dim array of 5 random nos

array([0.77043182, 0.37255967, 0.36877578, 0.81693491, 0.84917805])

In [52]:
np.random.rand(1)

array([0.22739752])

In [53]:
np.random.rand(2, 3)

array([[0.37704234, 0.34284683, 0.09245997],
       [0.91511125, 0.76965856, 0.8115633 ]])

In [54]:
np.random.randn(2, 3) #return a sample (or samples) from the "standard normal" distribution.

array([[ 0.94734897, -0.01831499,  0.40203937],
       [-0.69400529,  0.42822058, -1.10602302]])

In [55]:
np.random.randint(1, 5, size = (3, 4)) #start from 1 and end at 5-1 and give array of shape 3, 4

array([[3, 4, 3, 2],
       [1, 2, 1, 3],
       [2, 4, 2, 4]])

In [56]:
arr = np.random.randint(1, 5, size = (3, 4))

In [57]:
arr.ndim

2

In [58]:
arr.shape


(3, 4)

In [59]:
arr.size

12

In [60]:
arr

array([[1, 4, 3, 3],
       [3, 3, 1, 4],
       [1, 4, 4, 3]])

In [61]:
#reshaping of array
arr1 = arr.reshape(2, 6) #Returns an array containing the same data with a new shape.

In [62]:
arr1

array([[1, 4, 3, 3, 3, 3],
       [1, 4, 1, 4, 4, 3]])

In [63]:
arr1.size

12

In [65]:
arr1.shape

(2, 6)

In [66]:
arr1.ndim

2

In [67]:
#array size will never change, always reshape parameter should be multiplication of original array size

In [68]:
arr

array([[1, 4, 3, 3],
       [3, 3, 1, 4],
       [1, 4, 4, 3]])

In [ ]:
arr.reshape(3,2) #Gives error as the number of element is not equal

ValueError: cannot reshape array of size 12 into shape (3,2)

In [ ]:
arr.reshape(3,4) #No error as number of element is equal

array([[1, 4, 3, 3],
       [3, 3, 1, 4],
       [1, 4, 4, 3]])

In [ ]:
#case when we dont know in reshape what should be the row or column count
#use any negative value for rows or columns

arr.reshape(4,-1) #Row will be fixed as 4 and column is automatically adjusted

array([[1, 4, 3],
       [3, 3, 3],
       [1, 4, 1],
       [4, 4, 3]])

In [ ]:
arr.reshape(4,-100) #any negative number can be used

array([[1, 4, 3],
       [3, 3, 3],
       [1, 4, 1],
       [4, 4, 3]])

In [73]:
arr.reshape(-1,4) #Row will be automatically adjusted as per column 4

array([[1, 4, 3, 3],
       [3, 3, 1, 4],
       [1, 4, 4, 3]])

In [74]:
arr.reshape(12, 1).base #to see the original array

array([[1, 4, 3, 3],
       [3, 3, 1, 4],
       [1, 4, 4, 3]])

In [75]:
arr.reshape(2, 2, 3) #multiplication should be equals to arr sizev

array([[[1, 4, 3],
        [3, 3, 3]],

       [[1, 4, 1],
        [4, 4, 3]]])

In [76]:
arr.reshape(1, 2, 2, 3)

array([[[[1, 4, 3],
         [3, 3, 3]],

        [[1, 4, 1],
         [4, 4, 3]]]])

In [77]:
arr.reshape(1, 2, 2, 3).ndim

4

In [78]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[1],
        [4],
        [3]],

       [[3],
        [3],
        [3]],

       [[1],
        [4],
        [1]],

       [[4],
        [4],
        [3]]])

In [80]:
#conditions on array
arr1=np.random.randint(1, 10, (5, 6))
arr1

array([[3, 2, 5, 9, 1, 2],
       [6, 3, 3, 6, 6, 2],
       [2, 9, 9, 3, 5, 3],
       [3, 1, 5, 6, 1, 6],
       [1, 5, 1, 6, 4, 4]])

In [81]:
arr1.shape

(5, 6)

In [82]:
arr1.size

30

In [83]:
arr1.ndim

2

In [84]:
arr1

array([[3, 2, 5, 9, 1, 2],
       [6, 3, 3, 6, 6, 2],
       [2, 9, 9, 3, 5, 3],
       [3, 1, 5, 6, 1, 6],
       [1, 5, 1, 6, 4, 4]])

In [85]:
arr1 > 3

array([[False, False,  True,  True, False, False],
       [ True, False, False,  True,  True, False],
       [False,  True,  True, False,  True, False],
       [False, False,  True,  True, False,  True],
       [False,  True, False,  True,  True,  True]])

In [86]:
arr1[arr1 > 3] #select all the elements of arr1 where the condition is true

array([5, 9, 6, 6, 6, 9, 9, 5, 5, 6, 6, 5, 6, 4, 4])

In [87]:
arr1[arr1 < 3]

array([2, 1, 2, 2, 2, 1, 1, 1, 1])

In [88]:
arr1

array([[3, 2, 5, 9, 1, 2],
       [6, 3, 3, 6, 6, 2],
       [2, 9, 9, 3, 5, 3],
       [3, 1, 5, 6, 1, 6],
       [1, 5, 1, 6, 4, 4]])

In [90]:
# To access elements in an array

arr1[0]

array([3, 2, 5, 9, 1, 2])

In [91]:
arr1[1][2]

np.int64(3)

In [92]:
arr1

array([[3, 2, 5, 9, 1, 2],
       [6, 3, 3, 6, 6, 2],
       [2, 9, 9, 3, 5, 3],
       [3, 1, 5, 6, 1, 6],
       [1, 5, 1, 6, 4, 4]])

In [93]:
arr1[3][1]

np.int64(1)

In [94]:
#from 0th row to 2nd row
arr1[0:3]

array([[3, 2, 5, 9, 1, 2],
       [6, 3, 3, 6, 6, 2],
       [2, 9, 9, 3, 5, 3]])

In [95]:
#0 to 2nd row and 0th and 2nd column
arr1[0:3,[0, 2] ]

array([[3, 5],
       [6, 3],
       [2, 9]])

In [96]:
#slicing on both rows and columns together
arr1

array([[3, 2, 5, 9, 1, 2],
       [6, 3, 3, 6, 6, 2],
       [2, 9, 9, 3, 5, 3],
       [3, 1, 5, 6, 1, 6],
       [1, 5, 1, 6, 4, 4]])

In [97]:
arr1[0:3, 1:3]

array([[2, 5],
       [3, 3],
       [9, 9]])

In [98]:
arr1[0:3, [0, 1]]

array([[3, 2],
       [6, 3],
       [2, 9]])

In [ ]:
arr1[0, [1, 3]] #1st row and 2nd, 4th column only

array([2, 9])

In [100]:
arr1[2:4, [0, 3]]

array([[2, 3],
       [3, 6]])

In [101]:
arr1[2:5]

array([[2, 9, 9, 3, 5, 3],
       [3, 1, 5, 6, 1, 6],
       [1, 5, 1, 6, 4, 4]])

In [102]:
arr1[2:5, 0:2]

array([[2, 9],
       [3, 1],
       [1, 5]])

In [103]:
# Mathematical Operations on two arrays

arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [104]:
arr1

array([[2, 2, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [105]:
arr2

array([[2, 1, 1],
       [2, 2, 1],
       [2, 1, 1]])

In [106]:
arr1+arr2 #indexwise element addition

array([[4, 3, 3],
       [3, 4, 2],
       [3, 2, 3]])

In [107]:
arr1-arr2

array([[ 0,  1,  1],
       [-1,  0,  0],
       [-1,  0,  1]])

In [108]:
arr1 * arr2 #index wise multiplication

array([[4, 2, 2],
       [2, 4, 1],
       [2, 1, 2]])

In [109]:
arr1/arr2 #index wise divison

array([[1. , 2. , 2. ],
       [0.5, 1. , 1. ],
       [0.5, 1. , 2. ]])

In [111]:
4/0 #Gives error

ZeroDivisionError: division by zero

In [112]:
arr1/0 # GIves infinity

/tmp/ipykernel_1809/1006749343.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 # GIves infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [113]:
# Matrix Multiplication: matrix is a specialised 2-d array
# Matrix Multiplication is different from index wise multiplication

arr1 @ arr2

array([[12,  8,  6],
       [ 8,  6,  4],
       [ 8,  5,  4]])

In [114]:
np.dot(arr1, arr2) #another way of matrix multiplicationv

array([[12,  8,  6],
       [ 8,  6,  4],
       [ 8,  5,  4]])

In [115]:
arr1 * arr2

array([[4, 2, 2],
       [2, 4, 1],
       [2, 1, 2]])

In [116]:
# Broadcasting

arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [118]:
arr+5 #In broadcasting, 5 is added firstly 1st row, then 2nd row and then 3rd row

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [120]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [121]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [123]:
#Transpose: converting rows to columns and columns to rows
a = np.array([[1, 2, 3, 4]]) #It should be 2D array
a

array([[1, 2, 3, 4]])

In [124]:
a.T #Transpose

array([[1],
       [2],
       [3],
       [4]])