In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [3]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [4]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 2]])

In [5]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

array([1, 2, 1, 1, 1, 2, 2, 1, 2])

In [ ]:
#Expand Dimension
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [8]:
np.expand_dims(arr, axis=0) #increase the dimension by 1 in the provided axis, 0 means rows(x axis), 1 means column wise(y axis)

array([[1, 2, 3, 4]])

In [9]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.expand_dims(arr, axis=1).ndim

2

In [11]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.expand_dims(arr, axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
np.expand_dims(arr, axis = 0).ndim

3

In [14]:
np.expand_dims(arr, axis = 1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [15]:
a = np.array([[1], [2], [3]])
a

array([[1],
       [2],
       [3]])

In [ ]:
#Squeezing the dimension by 1 dimension
np.squeeze(a) #Remove axes of length one from `a`


array([1, 2, 3])

In [19]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [20]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [21]:
np.repeat(arr1, 2)

array([1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2])

In [22]:
np.repeat(arr1, 2, axis=0)

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 2],
       [1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [23]:
np.repeat(arr2, 3, axis=0)

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]])

In [24]:
np.repeat(arr2, 3, axis=1)

array([[2, 2, 2, 2, 2, 2, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 2, 2, 2, 2, 2]])

In [25]:
a

array([[1],
       [2],
       [3]])

In [26]:
np.roll(a, -1) #shift place

array([[2],
       [3],
       [1]])

In [27]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [28]:
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [30]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [31]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [32]:
arr1


array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [33]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 2]])

In [34]:
arr1+arr2

array([[3, 4, 2],
       [3, 2, 3],
       [3, 3, 4]])

In [35]:
arr1-arr2

array([[-1,  0,  0],
       [-1,  0,  1],
       [ 1, -1,  0]])

In [36]:
arr1 * arr2

array([[2, 4, 1],
       [2, 1, 2],
       [2, 2, 4]])

In [37]:
arr1 > arr2

array([[False, False, False],
       [False, False,  True],
       [ True, False, False]])

In [38]:
~arr1 #Negation of arr1

array([[-2, -3, -2],
       [-2, -2, -3],
       [-3, -2, -3]])

In [39]:
# Operations on numpy string array

d = np.array(["data", "science"])
d

array(['data', 'science'], dtype='<U7')

In [40]:
np.char.upper(d)

array(['DATA', 'SCIENCE'], dtype='<U7')

In [41]:
np.char.capitalize(d)

array(['Data', 'Science'], dtype='<U7')

In [42]:
# Mathematical Function

arr1

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [43]:
np.sin(arr1)

array([[0.84147098, 0.90929743, 0.84147098],
       [0.84147098, 0.84147098, 0.90929743],
       [0.90929743, 0.84147098, 0.90929743]])

In [44]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231, -0.41614684],
       [-0.41614684,  0.54030231, -0.41614684]])

In [45]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986,  1.55740772],
       [ 1.55740772,  1.55740772, -2.18503986],
       [-2.18503986,  1.55740772, -2.18503986]])

In [46]:
np.log10(arr1)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.30103]])

In [47]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [48]:
np.power(arr1, 3)

array([[1, 8, 1],
       [1, 1, 8],
       [8, 1, 8]])

In [ ]:
np.max(arr1) # Maximum value in arr1

np.int64(2)

In [52]:
np.min(arr1) #Minimum value in arr1

np.int64(1)

In [51]:
np.mean(arr1) #Average of arr1

np.float64(1.4444444444444444)

In [53]:
np.std(arr1) #Standard Deviation

np.float64(0.4969039949999533)

In [54]:
np.var(arr1) #Variance

np.float64(0.2469135802469136)

In [55]:
arr1-arr2

array([[-1,  0,  0],
       [-1,  0,  1],
       [ 1, -1,  0]])

In [56]:
np.subtract(arr1, arr2)

array([[-1,  0,  0],
       [-1,  0,  1],
       [ 1, -1,  0]])

In [57]:
arr1*arr2

array([[2, 4, 1],
       [2, 1, 2],
       [2, 2, 4]])

In [58]:
np.multiply(arr1, arr2)

array([[2, 4, 1],
       [2, 1, 2],
       [2, 2, 4]])

In [ ]:
np.mod(arr1, arr2) #Return element wise remainder

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [60]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356]])

In [62]:
# Sorting and Searching in numpy array
e = np.array([5, 6, 1, 2])
e

array([5, 6, 1, 2])

In [63]:
np.sort(e) #Return a sorted copy of an array.

array([1, 2, 5, 6])

In [64]:
f = np.array([5, 199, 200, 6, 7, 8])
f

array([  5, 199, 200,   6,   7,   8])

In [65]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [ ]:
np.searchsorted(f, 170) #Find indices where elements should be inserted to maintain order.(Gives 1 index extra as answer to be inserted)

np.int64(6)

In [67]:
f = np.array([5, 199, 200,0, 0, 0, 0, 6, 7, 8])
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [68]:
np.count_nonzero(f)

6

In [69]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [70]:
np.where(f>0) #same as above condition

(array([0, 1, 2, 7, 8, 9]),)

In [71]:
np.extract(f>0, f) #same as above condition

array([  5, 199, 200,   6,   7,   8])

In [72]:
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [73]:
f.byteswap() #Swap the bytes of the array elements

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
                          0,                    0,                    0,
                          0,   432345564227567616,   504403158265495552,
         576460752303423488])

In [74]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [75]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
# Numpy Linear Algebra

arr1

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [77]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 2]])

In [78]:
arr1@arr2 #Matrix Multiplication

array([[7, 6, 5],
       [6, 7, 6],
       [8, 9, 7]])

In [79]:
np.linalg.det(arr1) #To find Determinant

np.float64(2.9999999999999996)

In [80]:
np.linalg.det(arr2)

np.float64(-2.9999999999999996)

In [81]:
# In matrix, we can not divide by another matrix, but we have inverse
np.linalg.inv(arr2)

array([[ 0.        ,  0.66666667, -0.33333333],
       [ 1.        , -1.        , -0.        ],
       [-1.        ,  0.66666667,  0.66666667]])

In [82]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [83]:
b = np.array([16, 8, 0])

In [84]:
np.linalg.solve(a, b) # To solve Linear Algebra Equation (x,y,z,etc.)

array([2.59630607, 0.84432718, 2.21635884])